src/Entity/Voiture.php
<?php

namespace App\Entity;

use App\Repository\VoitureRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VoitureRepository::class)
 */
class Voiture
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20, unique=true)
     */
    private $Matricule;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $Marque;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $Couleur;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $Carburant;

    /**
     * @ORM\Column(type="integer")
     */
    private $places;

    /**
     * @ORM\Column(type="string", length=300)
     */
    private $Description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Disponibilite;

    /**
     * @ORM\Column(type="date")
     */
    private $datemiseencirculation;

    /**
     * @ORM\Column(type="string")
     */
    private $idAgence;

    public function getId(): ?int
    {
        return $this->id;
    }
    public function __toString()
    {
        return $this->Matricule;
    }
    public function getMatricule(): ?string
    {
        return $this->Matricule;
    }

    public function setMatricule(string $Matricule): self
    {
        $this->Matricule = $Matricule;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->Marque;
    }

    public function setMarque(string $Marque): self
    {
        $this->Marque = $Marque;

        return $this;
    }

    public function getCouleur(): ?string
    {
        return $this->Couleur;
    }

    public function setCouleur(string $Couleur): self
    {
        $this->Couleur = $Couleur;

        return $this;
    }

    public function getCarburant(): ?string
    {
        return $this->Carburant;
    }

    public function setCarburant(string $Carburant): self
    {
        $this->Carburant = $Carburant;

        return $this;
    }

    public function getPlaces(): ?int
    {
        return $this->places;
    }

    public function setPlaces(int $places): self
    {
        $this->places = $places;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getDisponibilite(): ?bool
    {
        return $this->Disponibilite;
    }

    public function setDisponibilite(bool $Disponibilite): self
    {
        $this->Disponibilite = $Disponibilite;

        return $this;
    }

    public function getDatemiseencirculation(): ?\DateTimeInterface
    {
        return $this->datemiseencirculation;
    }

    public function setDatemiseencirculation(\DateTimeInterface $datemiseencirculation): self
    {
        $this->datemiseencirculation = $datemiseencirculation;

        return $this;
    }

    public function getIdAgence(): ?string
    {
        return $this->idAgence;
    }

    public function setIdAgence(string $idAgence): self
    {
        $this->idAgence = $idAgence;

        return $this;
    }
}

templates/dashboard/cars.html.twig
<!DOCTYPE html>

{% block body %}
	<br/>
	{% if availableCars %}
		<h1>All Available Cars</h1>
		<table id="availableCars" class="table table-striped">
			<thead>
				<tr>
					<th>Mark</th>
					<th>Matricule</th>
					<th>Color</th>
					<th>Places</th>
					<th>Availability</th>
					<th>Agency</th>
					{% if app.user.roles[0] == "ROLE_ADMIN" %}
					<th>Actions</th>
					{% endif %}
				</tr>
			</thead>
			<tbody>
				{% for voiture in availableCars %}
					<tr>
						<td>{{ voiture.marque }}</td>
						<td>{{ voiture.matricule }}</td>
						<td>{{ voiture.couleur }}</td>
						<td>{{ voiture.places }}</td>
						{% if voiture.Disponibilite == 0 %}
							<td>Not</td>
						{% else %}
							<td>Yes</td>
						{% endif %}
						<td>{{ voiture.idAgence }}</td>
						{% if app.user.roles[0] == "ROLE_ADMIN" %}
						<td>
							<a href="/admin/car/{{ voiture.id }}" class="btn btn-dark">Show</a>
							<a href="/admin/car/edit/{{ voiture.id }}" class="btn btn-light">Edit</a>
							<a href="/admin/car/delete/{{ voiture.id }}" class="btn btn-danger delete-voiture" data-id="{{ voiture.id }}">Delete</a>
						</td>
						{% endif %}
					</tr>
				{% endfor %}
			</tbody>
		</tbody>
	</table>
{% else %}
	<h1>0 Available Cars Was Found!</h1>
{% endif %}
<br/>
<br/>
{% if notAvailableCars %}
	<h1>All Cars Not Available</h1>
	<table id="notAvailableCars" class="table table-striped">
		<thead>
			<tr>
				<th>Mark</th>
				<th>Matricule</th>
				<th>Color</th>
				<th>Places</th>
				<th>Availability</th>
				<th>Agency</th>
				{% if app.user.roles[0] == "ROLE_ADMIN" %}
					<th>Actions</th>
				{% endif %}
			</tr>
		</thead>
		<tbody>
			{% for voiture in notAvailableCars %}
				<tr>
					<td>{{ voiture.marque }}</td>
					<td>{{ voiture.matricule }}</td>
					<td>{{ voiture.couleur }}</td>
					<td>{{ voiture.places }}</td>
					{% if voiture.Disponibilite == 0 %}
						<td>Not</td>
					{% else %}
						<td>Yes</td>
					{% endif %}
					<td>{{ voiture.idAgence }}</td>
					{% if app.user.roles[0] == "ROLE_ADMIN" %}
						<td>
							<a href="/admin/car/{{ voiture.id }}" class="btn btn-dark">Show</a>
							<a href="/admin/car/edit/{{ voiture.id }}" class="btn btn-light">Edit</a>
							<a href="/admin/car/delete/{{ voiture.id }}" class="btn btn-danger delete-voiture" data-id="{{ voiture.id }}">Delete</a>
						</td>
					{% endif %}
				</tr>
			{% endfor %}
		</tbody>
	</tbody>
</table>{% else %}
<h1>0 Cars To Give Back Was Found!</h1>{% endif %}{% endblock %}

templates/dashboard/factures.html.twig
<br/>
<br/>
{% block body %}
	{% if factures %}
		<h1>All Unpayed Bills</h1>
		<table id="factures" class="table table-striped">
			<thead>
				<tr>
					<th>#</th>
					<th>Client</th>
					<th>Montant</th>
					<th>Payee</th>
				</tr>
			</thead>
			<tbody>
				{% for facture in factures %}
					<tr>
						<td>{{ facture.id }}</td>
						<td>{{ facture.idClient }}</td>
						<td>{{ facture.Montant }}dt</td>
						{% if facture.Payee == 0 %}
							<td>Not Payed</td>
						{% else %}
							<td>Yes</td>
						{% endif %}
						{% if facture.Payee == 0 %}
						<td>
							<a href="/agent/facture/pay/{{ facture.id }}" class="btn btn-danger delete-contrat" data-id="{{ facture.id }}">Pay</a>
						</td>
						{% endif %}
					</tr>
				{% endfor %}
			</tbody>
		</table>
	{% else %}
		<h1>All Bills Are Payed</h1>
	{% endif %}
{% endblock %}

templates/dashboard/index.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %}Welcome to SymphRide!
			{% endblock %}
		</title>
		<link rel="stylesheet" href="https://bootswatch.com/4/cosmo/bootstrap.min.css"> {% block stylesheets %}{% endblock %}
		</head>
		<body>
			{{ include('inc/navbar.html.twig') }}
			<div class="container">
				{% block body %}
					{% if app.user.roles[0] == "ROLE_AGENT" %}
						{{ include('dashboard/cars.html.twig') }}
						{{ include('dashboard/factures.html.twig') }}
					{% endif %}
					{% if app.user.roles[0] == "ROLE_ADMIN" %}
						<br/>
						<h1>Welcome to SymphRide!</h1>
					{% endif %}
				{% endblock %}
			</body>
		</body>
	</html>
</div></body></html>